// Generated by cpp11: do not edit by hand
// clang-format off

#include <cpp11/R.hpp>
#include <Rcpp.h>
using namespace Rcpp;
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// cpp_functions.cpp
void fun();
extern "C" SEXP _clubpro_fun() {
  BEGIN_CPP11
    fun();
    return R_NilValue;
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _clubpro_c_binary_procrustes_rotation(SEXP, SEXP);
extern SEXP _clubpro_c_classify(SEXP, SEXP);
extern SEXP _clubpro_c_dichotemise_matrix(SEXP);
extern SEXP _clubpro_c_normalise_matrix(SEXP);
extern SEXP _clubpro_c_to_indicator_matrix(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_clubpro_c_binary_procrustes_rotation", (DL_FUNC) &_clubpro_c_binary_procrustes_rotation, 2},
    {"_clubpro_c_classify",                   (DL_FUNC) &_clubpro_c_classify,                   2},
    {"_clubpro_c_dichotemise_matrix",         (DL_FUNC) &_clubpro_c_dichotemise_matrix,         1},
    {"_clubpro_c_normalise_matrix",           (DL_FUNC) &_clubpro_c_normalise_matrix,           1},
    {"_clubpro_c_to_indicator_matrix",        (DL_FUNC) &_clubpro_c_to_indicator_matrix,        1},
    {"_clubpro_fun",                          (DL_FUNC) &_clubpro_fun,                          0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_clubpro(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
