// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// c_to_indicator_matrix
NumericMatrix c_to_indicator_matrix(NumericVector v);
RcppExport SEXP _clubpro_c_to_indicator_matrix(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(c_to_indicator_matrix(v));
    return rcpp_result_gen;
END_RCPP
}
// c_normalise_matrix
NumericMatrix c_normalise_matrix(NumericMatrix A);
RcppExport SEXP _clubpro_c_normalise_matrix(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(c_normalise_matrix(A));
    return rcpp_result_gen;
END_RCPP
}
// c_dichotemise_matrix
NumericMatrix c_dichotemise_matrix(NumericMatrix A);
RcppExport SEXP _clubpro_c_dichotemise_matrix(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(c_dichotemise_matrix(A));
    return rcpp_result_gen;
END_RCPP
}
// c_binary_procrustes_rotation
NumericMatrix c_binary_procrustes_rotation(NumericVector x, NumericVector y);
RcppExport SEXP _clubpro_c_binary_procrustes_rotation(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(c_binary_procrustes_rotation(x, y));
    return rcpp_result_gen;
END_RCPP
}
// c_classify
List c_classify(NumericVector obs, NumericVector target);
RcppExport SEXP _clubpro_c_classify(SEXP obsSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    rcpp_result_gen = Rcpp::wrap(c_classify(obs, target));
    return rcpp_result_gen;
END_RCPP
}
// c_rand_pccs
NumericVector c_rand_pccs(NumericVector obs, NumericVector target, int nreps);
RcppExport SEXP _clubpro_c_rand_pccs(SEXP obsSEXP, SEXP targetSEXP, SEXP nrepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< int >::type nreps(nrepsSEXP);
    rcpp_result_gen = Rcpp::wrap(c_rand_pccs(obs, target, nreps));
    return rcpp_result_gen;
END_RCPP
}
